// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVBiVa4FurNVzzk6leTQqtciyq_jf4iCg',
    appId: '1:248665991435:web:a2e064378da52e349d1a0e',
    messagingSenderId: '248665991435',
    projectId: 'rotc-app-6bfa6',
    authDomain: 'rotc-app-6bfa6.firebaseapp.com',
    storageBucket: 'rotc-app-6bfa6.appspot.com',
    measurementId: 'G-JD7YZG06SE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWI8lHIHC-t6R-bPy8RIV7HwOqD3C2a5I',
    appId: '1:248665991435:android:161e9c9fca806ad69d1a0e',
    messagingSenderId: '248665991435',
    projectId: 'rotc-app-6bfa6',
    storageBucket: 'rotc-app-6bfa6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC__hpyvZ_SQI6ArcYCDc0v6fSNu87MdJI',
    appId: '1:248665991435:ios:20bd352748a77beb9d1a0e',
    messagingSenderId: '248665991435',
    projectId: 'rotc-app-6bfa6',
    storageBucket: 'rotc-app-6bfa6.appspot.com',
    iosClientId: '248665991435-6iu82qic3710l9gm1aacjrqdram7m4ic.apps.googleusercontent.com',
    iosBundleId: 'com.battalion-connect.app',
  );
}
